// Actions to search jobs
export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_ALL_JOB_TITLES = 'GET_ALL_JOB_TITLES';
export const GET_ALL_JOBS_RELATED_JOBS = 'GET_ALL_JOBS_RELATED_JOBS';
export const GET_ALL_JOBS_RELATED_SKILLS = 'GET_ALL_JOBS_RELATED_SKILLS';
export const GET_ALL_JOBS_KEYWORDS = 'GET_ALL_JOBS_KEYWORDS';

// Actions to search skills
export const GET_ALL_SKILLS = 'GET_ALL_SKILLS';
export const GET_ALL_SKILL_TITLES = 'GET_ALL_SKILL_TITLES';
export const GET_ALL_SKILLS_RELATED_JOBS = 'GET_ALL_SKILLS_RELATED_JOBS';
export const GET_ALL_SKILLS_RELATED_SKILLS = 'GET_ALL_SKILLS_RELATED_JOBS';
export const GET_ALL_SKILLS_KEYWORDS = 'GET_ALL_SKILLS_KEYWORDS';


